spring:
  application:
    name: rapid
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://168.107.27.154:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: k2512p1t2
    password: km2512p1t2
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml