spring:
  application:
    name: rapid
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://proxogus.codns.com:32270/rapid?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: rapid_user
    password: rapid!234
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
